version: '2'

volumes:
    mysqldata:
        driver: local
    redisdata:
        driver: local

networks:
    backend:
        driver: bridge

services:

  app-backend:
    build: 
      context: ./docker/php
      args:
        - GITHUB_TOKEN=4bcb0723438da7cf1e8231fda18647a5b5ab0d9b    
    restart: always
    volumes:
      - ./:/app
    expose:
      - 9000
    networks:
      - backend
    depends_on:
      - proxy        

  app-frontend:
    build: 
      context: ./docker/php
      args:
        - GITHUB_TOKEN=4bcb0723438da7cf1e8231fda18647a5b5ab0d9b    
    restart: always
    volumes_from:
      - app-backend
    depends_on:
      - app-backend        
    expose:
      - 9000
    networks:
      - backend

  frontend:
    image: nginx:1.12-alpine
    restart: always
    ports:
      - "7001:80"
    volumes_from:
      - app-backend
    depends_on:
      - app-backend        
    volumes:
      - ./docker/nginx/conf.d/frontend.conf:/etc/nginx/conf.d/default.conf
    networks:
      - backend

  backend:
    image: nginx:1.12-alpine
    restart: always
    ports:
      - "7002:80"
    volumes_from:
      - app-backend  
    depends_on:
      - app-backend        
    volumes:
      - ./docker/nginx/conf.d/backend.conf:/etc/nginx/conf.d/default.conf
    networks:
      - backend         

  proxy:
    build: 
      context: ./docker/openresty
    ports:
      - 80:80
    restart: always
    networks:
      - backend 

  db:
    image: mariadb:10.1
    restart: always
    volumes:
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
      - ./docker/mysql/initdb:/docker-entrypoint-initdb.d
      - "mysqldata:/var/lib/mysql"
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root@jib
      MYSQL_DATABASE: fids
      MYSQL_USER: fids@jib
      MYSQL_PASSWORD: 123132123
    networks:
      - backend

  redis:
    image: redis:3.2.6-alpine
    restart: always
    expose:
      - "6379"
    volumes:
      - "redisdata:/data"
    networks:
      - backend