<?php
/**
 * Created by PhpStorm.
 * User: ilyas
 * Date: 6/18/2017 AD
 * Time: 5:42 PM
 */

namespace console\migrations\fid\components;
use console\components\Migration as BaseMigration;

class Migration extends BaseMigration
{
    CONST USER_TABLE = '{{%user}}';
    /**
     * Please note that it's specific for database which has CURRENT_TIMESTAMP / ON UPDATE CURRENT_TIMESTAMP.
     * @param $table
     * @param $columns
     * @param null $options
     */
    public function createTableWithBlameAndTimestamp($table, $columns, $options = null)
    {
        $this->createTable($table, array_merge($columns, [
            'created_at' => 'DATETIME NULL DEFAULT CURRENT_TIMESTAMP',
            'updated_at' => 'DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP',
            'created_by' => $this->bigInteger(),
            'updated_by' => $this->bigInteger(),
        ]), $options);
        $this->addForeignKeyWithAutoGeneratedName($table, 'created_by', self::USER_TABLE, 'id', 'RESTRICT', 'CASCADE');
        $this->addForeignKeyWithAutoGeneratedName($table, 'updated_by', self::USER_TABLE, 'id', 'RESTRICT', 'CASCADE');
        // Add comments
        $this->addCommentOnColumn($table, 'updated_at', 'วันเวลาที่สร้าง');
        $this->addCommentOnColumn($table, 'updated_at', 'วันเวลาที่แก้ไขล่าสุด');
        $this->addCommentOnColumn($table, 'created_by', 'ผู้ใช้งานที่สร้าง');
        $this->addCommentOnColumn($table, 'updated_by', 'ผู้ใช้งานที่แก้ไขล่าสุด');
    }
}
