<?php

use  console\migrations\fid\components\Migration;

/**
 * Handles the creation of table `person`.
 */
class m170617_044450_create_person_table extends Migration
{
    const PERSON_TABLE_NAME = '{{%person}}';
    const PERSON_GROUP_TABLE_NAME = '{{%person_group}}';
    const FILE_STORAGE_ITEM_TABLE_NAME = '{{%file_storage_item}}';

    // Support Tables
    const RACE_TABLE_NAME = '{{%person_race}}';
    const NATIONALITY_TABLE_NAME = '{{%person_nationality}}';
    const BLOOD_TYPE_TABLE_NAME = '{{%person_blood_type}}';
    const RELIGION_TABLE_NAME = '{{%person_religion}}';
    const GENDER_TABLE_NAME = '{{%person_gender}}';
    const MILITARY_STATUS_TABLE_NAME = '{{%person_military_status}}';
    const MARRIAGE_STATUS_TABLE_NAME = '{{%person_marriage_status}}';
    // Address
    const SUBDISTRICT_TABLE_NAME = '{{%addr_subdistrict}}';
    const DISTRICT_TABLE_NAME = '{{%addr_district}}';
    const PROVINCE_TABLE_NAME = '{{%addr_province}}';
    const COUNTRY_TABLE_NAME = '{{%addr_country}}';

    /**
     * @inheritdoc
     */
    public function up()
    {
        $this->createTableWithBlameAndTimestamp(self::PERSON_TABLE_NAME, [
            'id' => $this->bigInteger()->notNull(),
            'person_group_id' => [
                'type' => $this->bigInteger(),
                'fk' => self::PERSON_GROUP_TABLE_NAME,
            ],
            'image_id' => $this->integer(),
            // === Personal Information ===
            // Identification Card
            'id_number' => $this->string(),
            'id_card_issue_date' => $this->date(),
            'id_card_issue_at' => $this->string(),
            'id_card_expiry_date' => $this->date(),
            // Passport
            'passport_number' => $this->string(),
            // Name en
            'th_title_name' => $this->string(),
            'th_first_name' => $this->string(),
            'th_middle_name' => $this->string(),
            'th_last_name' => $this->string(),
            'th_nickname' => $this->string(),
            // Name th
            'en_title_name' => $this->string(),
            'en_first_name' => $this->string(),
            'en_middle_name' => $this->string(),
            'en_last_name' => $this->string(),
            'en_nickname' => $this->string(),
            'raceId' => [
                'type' => $this->integer(),
                'fk' => self::RACE_TABLE_NAME,
            ],
            'nationality_id' => [
                'type' => $this->integer(),
                'fk' => self::NATIONALITY_TABLE_NAME,],
            'blood_type_id' => [
                'type' => $this->integer(),
                'fk' => self::BLOOD_TYPE_TABLE_NAME],
            'religion_id' => [
                'type' => $this->integer(),
                'fk' => self::RELIGION_TABLE_NAME],
            'gender_id' => [
                'type' => $this->integer(),
                'fk' => self::GENDER_TABLE_NAME],
            'military_status_id' => [
                'type' => $this->integer(),
                'fk' => self::MILITARY_STATUS_TABLE_NAME
            ],
            'marriage_status_id' => [
                'type' => $this->integer(),
                'fk' => self::MARRIAGE_STATUS_TABLE_NAME
            ],
            'birthdate' => $this->date(),
            'occupation' => $this->string(),
            // === Contact Information ===
            // Address
            'address' => $this->text(),
            'subdistrictId' => [
                'type' => $this->integer(),
                'fk' => self::SUBDISTRICT_TABLE_NAME
            ],
            'districtId' => [
                'type' => $this->integer(),
                'fk' => self::DISTRICT_TABLE_NAME
            ],
            'province_id' => [
                'type' => $this->integer(),
                'fk' => self::PROVINCE_TABLE_NAME
            ],
            'country_id' => [
                'type' => $this->integer(),
                'fk' => self::COUNTRY_TABLE_NAME
            ],
            'postal_code' => $this->string(),
            // Phone & Social
            'phone_number' => $this->string(),
            'mobile_number' => $this->string(),
            'work_number' => $this->string(),
            'fax_number' => $this->string(),
            'other_number' => $this->string(),
            'email' => $this->string(),
            'facebook' => $this->string(),
            'twitter' => $this->string(),
            'line' => $this->string(),
            // Note
            'note' => $this->text(),
            // Support
            'active' => $this->boolean()->defaultValue(true)->notNull(),
        ]);
        $this->addPrimaryKeyWithAutoGeneratedName(self::PERSON_TABLE_NAME,'id');
        $this->addCommentOnColumn(self::PERSON_TABLE_NAME, 'image_id', 'ไอดีที่อยู่ในระบบของรูปภาพประจำตัว');
        $this->addCommentOnColumn(self::PERSON_TABLE_NAME, 'id_number', 'เลขบัตรประชาชน');
        $this->addCommentOnColumn(self::PERSON_TABLE_NAME, 'id_card_issue_date', 'วันออกบัตรประชาชน');
        $this->addCommentOnColumn(self::PERSON_TABLE_NAME, 'id_card_issue_at', 'สถานที่ออกบัตรประชาชน');
        $this->addCommentOnColumn(self::PERSON_TABLE_NAME, 'id_card_expiry_date', 'วันหมดอายุบัตรประชาชน');
        $this->addCommentOnColumn(self::PERSON_TABLE_NAME, 'note', 'หมายเหตุ');
        $this->addCommentOnActiveColumn(self::PERSON_TABLE_NAME);
    }

    /**
     * @inheritdoc
     */
    public function down()
    {
        $this->dropTable(self::PERSON_TABLE_NAME);
    }
}
