<?php

use  console\migrations\fid\components\Migration;

/**
 * Handles the creation of table `item`.
 */
class m170617_044849_create_item_table extends Migration
{
    const ITEM_TABLE_NAME = '{{%item}}';
    const ITEM_GROUP_TABLE_NAME = '{{%item_group}}';

    /**
     * @inheritdoc
     */
    public function up()
    {
        $this->createTableWithBlameAndTimestamp(self::ITEM_TABLE_NAME, [
            'id' => $this->bigInteger()->notNull(),
            'item_group_id' => [
                'type' => $this->bigInteger(),
                'fk' => self::ITEM_GROUP_TABLE_NAME,
            ],
            'name' => $this->string()->notNull(),
            'description' => $this->string(),
            'identification1' => ['type' => $this->string(), 'idx' => true],
            'identification2' => ['type' => $this->string(), 'idx' => true],
            'identification3' => ['type' => $this->string(), 'idx' => true],
            'identification4' => ['type' => $this->string(), 'idx' => true],
            'identification5' => ['type' => $this->string(), 'idx' => true],
            'active' => $this->boolean()->defaultValue(true)->notNull(),
        ]);
        $this->addPrimaryKeyWithAutoGeneratedName(self::ITEM_TABLE_NAME,'id');           
        $this->addCommentOnColumn(self::ITEM_TABLE_NAME, 'identification1', 'ข้อมูลยืนยันสิ่งของ 1');
        $this->addCommentOnColumn(self::ITEM_TABLE_NAME, 'identification2', 'ข้อมูลยืนยันสิ่งของ 2');
        $this->addCommentOnColumn(self::ITEM_TABLE_NAME, 'identification3', 'ข้อมูลยืนยันสิ่งของ 3');
        $this->addCommentOnColumn(self::ITEM_TABLE_NAME, 'identification4', 'ข้อมูลยืนยันสิ่งของ 4');
        $this->addCommentOnColumn(self::ITEM_TABLE_NAME, 'identification5', 'ข้อมูลยืนยันสิ่งของ 5');
        $this->addCommentOnActiveColumn(self::ITEM_TABLE_NAME);
    }

    /**
     * @inheritdoc
     */
    public function down()
    {
        $this->dropTable(self::ITEM_TABLE_NAME);
    }
}
