<?php

use  console\migrations\fid\components\Migration;

/**
 * Handles the creation of table `case`.
 */
class m170618_044914_create_case_and_entities_relationship_tables extends Migration
{
    const CASE_PERSON_TABLE_NAME = '{{%case_person}}';
    const CASE_PLACE_TABLE_NAME = '{{%case_place}}';

    const CASE_ITEM_TABLE_NAME = '{{%case_items}}';

    const PERSON_PLACE_TABLE_NAME = '{{%person_place}}';
    const PERSON_ITEM_TABLE_NAME = '{{%person_item}}';
    const PLACE_ITEM_TABLE_NAME = '{{%place_item}}';

    const CASE_RELATIONSHIP_TABLES = [
        self::CASE_PERSON_TABLE_NAME,
        self::CASE_PLACE_TABLE_NAME,
        self::CASE_ITEM_TABLE_NAME,
    ];

    const ENTITY_RELATIONSHIP_TABLES = [
        self::PERSON_PLACE_TABLE_NAME,
        self::PERSON_ITEM_TABLE_NAME,
        self::PLACE_ITEM_TABLE_NAME,
    ];

    const CASE_TABLE_NAME = '{{%case}}';
    const PERSON_TABLE_NAME = '{{%person}}';
    const PLACE_TABLE_NAME = '{{%place}}';
    const ITEM_TABLE_NAME = '{{%item}}';

    /**
     * @inheritdoc
     */
    public function up()
    {
            $this->createTableWithBlameAndTimestamp($this->addPercentSignAndCurlyBraces('case_items_type'), [
                 'id' => $this->bigInteger()->notNull(),
                 'name' => $this->string()->notNull(),
                 'group' => $this->string(),
            ]);
            $this->addPrimaryKeyWithAutoGeneratedName('case_items_type','id');  

            $this->createTableWithBlameAndTimestamp('case_items', [
                'id' => $this->bigInteger()->notNull(),
                'case_items_type_id' => $this->bigInteger()->notNull(),
                'case_id' => $this->bigInteger()->notNull(),
                'item_id' => $this->bigInteger()->notNull()->defaultValue(0),
                'place_id' => $this->bigInteger()->notNull()->defaultValue(0),
                'person_id' => $this->bigInteger()->notNull()->defaultValue(0)
            ]);

            $this->addPrimaryKeyWithAutoGeneratedName('case_items','id');  
            $this->createIndexWithAutoGeneratedName('case_items','case_items_type_id');
            $this->createIndexWithAutoGeneratedName('case_items','case_id');
            $this->createIndexWithAutoGeneratedName('case_items','item_id');
            $this->createIndexWithAutoGeneratedName('case_items','place_id');
            $this->createIndexWithAutoGeneratedName('case_items','person_id');
    }

    /**
     * @inheritdoc
     */
    public function down()
    {

    }
}
