<?php
use  console\migrations\fid\components\Migration;

/**
 * Handles the creation of table `case`.
 */
class m170617_044900_create_case_type_table extends Migration
{
    const TABLE_NAME = '{{%case_type}}';

    /**
     * @inheritdoc
     */
    public function up()
    {
        $this->createTableWithBlameAndTimestamp(self::TABLE_NAME, [
            'id' => $this->bigInteger()->notNull(),
            'name' => $this->string()->notNull(),
            'description' => $this->text(),
            'weight' => $this->smallInteger()->notNull()->defaultValue(999),
            'active' => $this->boolean()->notNull()->defaultValue(true),
        ]);
        $this->addPrimaryKeyWithAutoGeneratedName(self::TABLE_NAME,'id');            
        $this->addCommentOnWeightColumn(self::TABLE_NAME);
        $this->addCommentOnActiveColumn(self::TABLE_NAME);
    }

    /**
     * @inheritdoc
     */
    public function down()
    {
        $this->dropTable(self::TABLE_NAME);
    }
}
