<?php

use  console\migrations\fid\components\Migration;

/**
 * Handles the creation of table `place`.
 */
class m170617_044843_create_place_table extends Migration
{
    const PLACE_TABLE_NAME = '{{%place}}';
    const PLACE_GROUP_TABLE_NAME = '{{%place_group}}';

    /**
     * @inheritdoc
     */
    public function up()
    {
        $this->createTableWithBlameAndTimestamp(self::PLACE_TABLE_NAME, [
            'id' => $this->bigInteger()->notNull(),
            'place_group_id' => [
                'type' => $this->bigInteger(),
                'fk' => self::PLACE_GROUP_TABLE_NAME,
            ],
            'name' => $this->string()->notNull(),
            'description' => $this->text(),
            'facility' => $this->string(),
            'subdistrict_id' => [
                'type' => $this->integer(),
                'fk' => '{{%addr_subdistrict}}',
            ],
            'district_id' => [
                'type' => $this->integer(),
                'fk' => '{{%addr_district}}',
            ],
            'province_id' => [
                'type' => $this->integer(),
                'fk' => '{{%addr_province}}',
            ],
            'postal_code' => $this->string(),
            'latitude' => 'FLOAT( 10, 6 )',
            'longitude' => 'FLOAT( 10, 6 )',
            'active' => $this->boolean()->defaultValue(true)->notNull(),
        ]);
        $this->addPrimaryKeyWithAutoGeneratedName(self::PLACE_TABLE_NAME,'id');        
        $this->addCommentOnColumn(self::PLACE_TABLE_NAME, 'latitude', 'ละติจูดที่ตั้งสถานที่');
        $this->addCommentOnColumn(self::PLACE_TABLE_NAME, 'longitude', 'ลองติจูดที่ตั้งสถานที่');
    }

    /**
     * @inheritdoc
     */
    public function down()
    {
        $this->dropTable(self::PLACE_TABLE_NAME);
    }
}
