<?php

use  console\migrations\fid\components\Migration;

/**
 * Handles the creation of table `case`.
 */
class m170617_044911_create_case_table extends Migration
{
    const CASE_TYPE_TABLE_NAME = '{{%case_type}}';
    const TABLE_NAME = '{{%case}}';

    /**
     * @inheritdoc
     */
    public function up()
    {
        $this->createTableWithBlameAndTimestamp(self::TABLE_NAME, [
            'id' => $this->bigInteger()->notNull(),
            'report_of' => $this->bigInteger(),
            'case_type_id' => [
                'type' => $this->bigInteger(),
                'fk' => self::CASE_TYPE_TABLE_NAME,
            ],
            'name' => $this->string()->notNull(),
            'description' => $this->text(),
            'occurred_at' => 'DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP',
            'active' => $this->boolean()->defaultValue(true)->notNull(),
        ]);
        $this->addPrimaryKeyWithAutoGeneratedName(self::TABLE_NAME,'id');      
        $this->addForeignKeyWithAutoGeneratedName(self::TABLE_NAME,'report_of',self::TABLE_NAME,'id');     
        $this->addCommentOnColumn(self::TABLE_NAME, 'report_of', 'ไอดีของเคสที่อ้างถึง (ระบุเมื่อเป็นเคสที่เป็นรายงาน)');
        $this->addCommentOnColumn(self::TABLE_NAME, 'case_type_id', 'ไอดีประเภทของเคส');
        $this->addCommentOnColumn(self::TABLE_NAME, 'occurred_at', 'วันเวลาเกิดเหตุการณ์');
        $this->addCommentOnActiveColumn(self::TABLE_NAME);
    }

    /**
     * @inheritdoc
     */
    public function down()
    {
        $this->dropTable(self::TABLE_NAME);
    }
}
