
gantt._formatLink=function(t){var e=[],n=this._get_link_target(t),a=this._get_link_source(t);if(!a||!n)return e;if(gantt.isChildOf(a.id,n.id)&&gantt._isProject(n)||gantt.isChildOf(n.id,a.id)&&gantt._isProject(a))return e;for(var i=this._getImplicitLinks(t,a,function(t){return 0}),r=gantt.config.auto_scheduling_move_projects,s=this._isProject(n)?this.getSubtaskDates(n.id):{start_date:n.start_date,end_date:n.end_date},o=this._getImplicitLinks(t,n,function(t){return r?t.$target.length?0:gantt.calculateDuration(gantt.roundDate(s.start_date),gantt.roundDate(t.start_date)):0;
}),_=0;_<i.length;_++)for(var l=i[_],d=0;d<o.length;d++){var g=o[d],h=l.lag+g.lag,c={id:t.id,type:t.type,source:l.task,target:g.task,lag:(t.lag||0)+h};e.push(gantt._convertToFinishToStartLink(g.task,c,a,n))}return e},gantt._getImplicitLinks=function(t,e,n){var a=[];return this._isProject(e)?this.eachTask(function(t){this._isProject(t)||a.push({task:t.id,lag:n(t)})},e.id):a.push({task:e.id,lag:0}),a},gantt._getDirectDependencies=function(t,e){for(var n=[],a=[],i=e?t.$source:t.$target,r=0;r<i.length;r++){
var s=this.getLink(i[r]);this.isTaskExists(s.source)&&this.isTaskExists(s.target)&&n.push(this.getLink(i[r]))}for(var r=0;r<n.length;r++)a=a.concat(this._formatLink(n[r]));return a},gantt._getInheritedDependencies=function(t,e){var n=[],a=[];if(this.isTaskExists(t.id)){this._eachParent(function(t){this._isProject(t)&&a.push.apply(a,this._getDirectDependencies(t,e))},t.id,this);for(var i=0;i<a.length;i++){var r=e?a[i].source:a[i].target;r==t.id&&n.push(a[i])}}return n},gantt._getDirectSuccessors=function(t){
return this._getDirectDependencies(t,!0)},gantt._getInheritedSuccessors=function(t){return this._getInheritedDependencies(t,!0)},gantt._getDirectPredecessors=function(t){return this._getDirectDependencies(t,!1)},gantt._getInheritedPredecessors=function(t){return this._getInheritedDependencies(t,!1)},gantt._getSuccessors=function(t){return this._getDirectSuccessors(t).concat(this._getInheritedSuccessors(t))},gantt._getPredecessors=function(t){return this._getDirectPredecessors(t).concat(this._getInheritedPredecessors(t));
},gantt._convertToFinishToStartLink=function(t,e,n,a){var i={target:t,link:gantt.config.links.finish_to_start,id:e.id,lag:e.lag||0,source:e.source,preferredStart:null},r=0;switch(e.type){case gantt.config.links.start_to_start:r=-n.duration;break;case gantt.config.links.finish_to_finish:r=-a.duration;break;case gantt.config.links.start_to_finish:r=-n.duration-a.duration;break;default:r=0}return i.lag+=r,i},gantt.config.auto_scheduling=!1,gantt.config.auto_scheduling_descendant_links=!1,gantt.config.auto_scheduling_initial=!0,
gantt.config.auto_scheduling_strict=!1,gantt.config.auto_scheduling_move_projects=!0,gantt._forEach=function(t,e){for(var n=t.slice(),a=0;a<n.length;a++)e(n[a],a)},gantt._arrayMap=function(t,e){for(var n=t.slice(),a=[],i=0;i<n.length;i++)a.push(e(n[i],i));return a},gantt._autoSchedulingGraph={getVertices:function(t){var e={};gantt._forEach(t,function(t){e[t.target]=t.target,e[t.source]=t.source});var n=[];for(var a in e)n.push(e[a]);return n.sort(function(t,e){return gantt.getGlobalTaskIndex(t)-gantt.getGlobalTaskIndex(e);
})},topologicalSort:function(t){for(var e=this.getVertices(t),n={},a=0;a<e.length;a++)n[e[a]]={id:e[a],$source:[],$target:[],$incoming:0};for(var a=0;a<t.length;a++){var i=n[t[a].target];i.$target.push(a),i.$incoming=i.$target.length,n[t[a].source].$source.push(a)}for(var r=e.filter(function(t){return!n[t].$incoming}),s=[];r.length;){var o=r.pop();s.push(o);for(var _=n[o],a=0;a<_.$source.length;a++){var l=n[t[_.$source[a]].target];l.$incoming--,l.$incoming||r.push(l.id)}}return s},tarjanStronglyConnectedComponents:function(t,e){
function n(t,i){var l=a(t);if(l.index=r,l.lowLink=r,r++,i&&o.push(i),s.push(l),l.onStack=!0,gantt._forEach(e,function(e){if(e.source==t){var i=a(e.source),r=a(e.target);void 0===r.index?(n(e.target,e),i.lowLink=Math.min(i.lowLink,r.lowLink)):r.onStack&&(i.lowLink=Math.min(i.lowLink,r.index),o.push(e))}}),l.lowLink==l.index){var d,g={tasks:[],links:[]};do{var h=o.pop();d=s.pop(),d.onStack=!1,g.tasks.push(d.id),h&&g.links.push(h.id)}while(d.id!=l.id);_.push(g)}}function a(t){return i[t]||(i[t]={id:t
}),i[t]}var i={},r=0,s=[],o=[],_=[];return gantt._forEach(t,function(t){var e=a(t);void 0===e.index&&n(t)}),_}},gantt._autoSchedulingPath={getKey:function(t){return[t.lag,t.link,t.source,t.target].join("_")},getVirtualRoot:function(){return gantt.mixin(gantt.getSubtaskDates(),{id:gantt.config.root_id,type:gantt.config.types.project,$source:[],$target:[],$virtual:!0})},filterDuplicates:function(t){for(var e={},n=0;n<t.length;n++){var a=this.getKey(t[n]);e[a]?(t.splice(n,1),n--):e[a]=!0}return t},getLinkedTasks:function(t,e){
for(var n=[t],a=[],i={},r=0;r<n.length;r++)a=a.concat(this._getLinkedTasks(n[r],i,e));return a},_getLinkedTasks:function(t,e,n){var a=void 0===t?gantt.config.root_id:t,i=e||{},r=gantt.isTaskExists(a)?gantt.getTask(a):this.getVirtualRoot(),s=gantt._getSuccessors(r);n&&s.push.apply(s,gantt._getPredecessors(r));for(var o=[],_=0;_<s.length;_++)i[this.getKey(s[_])]||(i[this.getKey(s[_])]=!0,o=o.concat(this._getLinkedTasks(s[_].target,i,!0)));for(var l=gantt.getChildren(r.id),_=0;_<l.length;_++)s=s.concat(this._getLinkedTasks(l[_],i,!0));
return this.filterDuplicates(s.concat(o))},findLoops:function(t){var e=[];gantt._forEach(t,function(t){t.target==t.source&&e.push([t.target,t.source])});var n=gantt._autoSchedulingGraph,a=n.getVertices(t),i=n.tarjanStronglyConnectedComponents(a,t);return gantt._forEach(i,function(t){t.tasks.length>1&&e.push(t)}),e}},gantt._autoSchedulingDateResolver={isFirstSmaller:function(t,e){return t.valueOf()<e.valueOf()&&gantt._hasDuration(t,e)?!0:!1},isSmallerOrDefault:function(t,e){return!(t&&!this.isFirstSmaller(t,e));
},resolveRelationDate:function(t,e,n){for(var a=null,i=null,r=null,s=0;s<e.length;s++){var o=e[s];t=o.target,r=o.preferredStart;var _=this.getConstraintDate(o,n);this.isSmallerOrDefault(r,_)&&this.isSmallerOrDefault(a,_)&&(a=_,i=o.id)}return{link:i,task:t,start_date:a}},getConstraintDate:function(t,e){var n=e(t.source);return n&&t.lag&&1*t.lag==t.lag&&(n=gantt.calculateEndDate(n,1*t.lag)),n}},gantt._autoSchedulingPlanner={generatePlan:function(t){function e(t){var e=r[t],n=gantt.getTask(t);return e&&(e.start_date||e.end_date)?e.end_date?e.end_date:gantt.calculateEndDate(e.start_date,n.duration,gantt.config.duration_unit):gantt.getClosestWorkTime({
date:n.end_date,dir:"future"})}var n=gantt._autoSchedulingGraph,a=n.topologicalSort(t),i={},r={};gantt._arrayMap(a,function(t){var e=gantt.getTask(t);e.auto_scheduling!==!1&&(i[t]=[],r[t]=null)});for(var s=0;s<t.length;s++)i[t[s].target].push(t[s]);for(var o=gantt._autoSchedulingDateResolver,_=[],s=0;s<a.length;s++){var l=a[s],d=o.resolveRelationDate(l,i[l],e);r[l]=d,d.start_date&&_.push(d)}return _},applyProjectPlan:function(t){for(var e,n,a,i,r=[],s=0;s<t.length;s++)if(a=null,i=null,e=t[s],e.task){
n=gantt.getTask(e.task),e.link&&(a=gantt.getLink(e.link),i=gantt.getTask(a.source));var o=null;if(e.start_date&&n.start_date.valueOf()!=e.start_date.valueOf()&&(o=e.start_date),o){if(gantt.callEvent("onBeforeTaskAutoSchedule",[n,o,a,i])===!1)break;n.start_date=o,n.end_date=gantt.calculateEndDate(n.start_date,n.duration,gantt.config.duration_unit),r.push(n.id),gantt.callEvent("onAfterTaskAutoSchedule",[n,o,a,i])}}return r}},gantt._autoSchedulingPreferredDates=function(t,e){for(var n=0;n<e.length;n++){
var a=e[n],i=gantt.getTask(a.target);gantt.config.auto_scheduling_strict&&a.target!=t||(a.preferredStart=new Date(i.start_date))}},gantt._autoSchedule=function(t,e,n){if(gantt.callEvent("onBeforeAutoSchedule",[t])!==!1){gantt._autoscheduling_in_progress=!0;var a=gantt._autoSchedulingPath,i=[],r=a.findLoops(e);if(r.length)gantt.callEvent("onAutoScheduleCircularLink",[r]);else{var s=gantt._autoSchedulingPlanner;gantt._autoSchedulingPreferredDates(t,e);var o=s.generatePlan(e);i=s.applyProjectPlan(o),
n&&n(i)}return gantt._autoscheduling_in_progress=!1,gantt.callEvent("onAfterAutoSchedule",[t,i]),i}},gantt.autoSchedule=function(t,e){e=void 0===e?!0:!!e;var n=gantt._autoSchedulingPath.getLinkedTasks(t,e);gantt._autoSchedule(t,n,gantt._finalizeAutoSchedulingChanges)},gantt._finalizeAutoSchedulingChanges=function(t){gantt.batchUpdate(function(){for(var e=0;e<t.length;e++)gantt.updateTask(t[e])})},gantt.isCircularLink=function(t){return!!gantt._getConnectedGroup(t)},gantt._getConnectedGroup=function(t){
var e=gantt._autoSchedulingPath,n=e.getLinkedTasks();gantt.isLinkExists(t.id)||(n=n.concat(gantt._formatLink(t)));for(var a=e.findLoops(n),i=!1,r=0;r<a.length&&!i;r++)for(var s=a[r].links,o=0;o<s.length;o++)if(s[o]==t.id)return a[r];return null},gantt.findCycles=function(){var t=gantt._autoSchedulingPath,e=t.getLinkedTasks();return t.findLoops(e)},gantt._attachAutoSchedulingHandlers=function(){gantt._autoScheduleAfterLinkChange=function(t,e){gantt.config.auto_scheduling&&!this._autoscheduling_in_progress&&gantt.autoSchedule(e.source);
},gantt.attachEvent("onAfterLinkUpdate",gantt._autoScheduleAfterLinkChange),gantt.attachEvent("onAfterLinkAdd",gantt._autoScheduleAfterLinkChange),gantt.attachEvent("onParse",function(){gantt.config.auto_scheduling&&gantt.config.auto_scheduling_initial&&gantt.autoSchedule()}),gantt._preventCircularLink=function(t,e){return gantt.isCircularLink(e)?(gantt.callEvent("onCircularLinkError",[e,gantt._getConnectedGroup(e)]),!1):!0},gantt._preventDescendantLink=function(t,e){var n=gantt.getTask(e.source),a=gantt.getTask(e.target);
return!gantt.config.auto_scheduling_descendant_links&&(gantt.isChildOf(n.id,a.id)&&gantt._isProject(a)||gantt.isChildOf(a.id,n.id)&&gantt._isProject(n))?!1:!0},gantt.attachEvent("onBeforeLinkAdd",gantt._preventCircularLink),gantt.attachEvent("onBeforeLinkAdd",gantt._preventDescendantLink),gantt.attachEvent("onBeforeLinkUpdate",gantt._preventCircularLink),gantt.attachEvent("onBeforeLinkUpdate",gantt._preventDescendantLink),gantt._datesNotEqual=function(t,e){return t.valueOf()>e.valueOf()?this._hasDuration(e,t):this._hasDuration(t,e);
},gantt._notEqualTaskDates=function(t,e){return this._datesNotEqual(t.start_date,e.start_date)||(this._datesNotEqual(t.end_date,e.end_date)||t.duration!=e.duration)&&t.type!=gantt.config.types.milestone?!0:void 0};var t,e;gantt.attachEvent("onBeforeTaskDrag",function(n,a,i){return gantt.config.auto_scheduling_move_projects&&(t=gantt._autoSchedulingPath.getLinkedTasks(n,!0),e=n),!0}),gantt._autoScheduleAfterDND=function(n,a){if(gantt.config.auto_scheduling&&!this._autoscheduling_in_progress){var i=this.getTask(n);
gantt._notEqualTaskDates(a,i)&&(gantt.config.auto_scheduling_move_projects&&e==n?gantt._autoSchedule(n,t,gantt._finalizeAutoSchedulingChanges):gantt.autoSchedule(i.id))}return t=null,e=null,!0},gantt._lightBoxChangesHandler=function(t,e){if(gantt.config.auto_scheduling&&!this._autoscheduling_in_progress){var n=this.getTask(t);gantt._notEqualTaskDates(e,n)&&(gantt._autoschedule_lightbox_id=t)}return!0},gantt._lightBoxSaveHandler=function(t,e){return gantt.config.auto_scheduling&&!this._autoscheduling_in_progress&&gantt._autoschedule_lightbox_id&&gantt._autoschedule_lightbox_id==t&&(gantt._autoschedule_lightbox_id=null,
gantt.autoSchedule(e.id)),!0},gantt.attachEvent("onBeforeTaskChanged",function(t,e,n){return gantt._autoScheduleAfterDND(t,n)}),gantt.attachEvent("onLightboxSave",gantt._lightBoxChangesHandler),gantt.attachEvent("onAfterTaskUpdate",gantt._lightBoxSaveHandler)},gantt.attachEvent("onGanttReady",function(){gantt._attachAutoSchedulingHandlers()});
//# sourceMappingURL=../sources/ext/dhtmlxgantt_auto_scheduling.js.map